### ADD USER
POST {{hostUrl}}/user/add-user
Content-Type: application/json

{
"firstName": "yo",
"lastName": "Doe",
"username": "testUser1234",
"roleId": 1,
"email": "johndoe@example.com",
"password": "RealFilip33!",
"phoneNumber": "+1234567890",
"countryId": 123
}

### GET USERS
GET {{hostUrl}}/user/get-users
Accept: application/json

### GET USER
GET {{hostUrl}}/user/1

### ADD COUNTRY
POST {{hostUrl}}/country/add-country
Content-Type: application/json

{
"name": "United States",
"countryCode": "US",
"locale": "en-US"
}

### GET COUNTRIES
GET {{hostUrl}}/country/get-countries

### ADD ROOM - B2, B6
POST {{hostUrl}}/room/add-room
Content-Type: application/json

{
"name": "testna 6",
"userId": 1
}

### GET ROOMS - BASIC TASK 1 (B1)
GET {{hostUrl}}/room/get-rooms

### ROOM JOIN REQUEST - B3
POST {{hostUrl}}/roomUser/add-room-user/1
Content-Type: application/json

{
"userId": 1,
"roomId": 1
}

### SEND/ADD MESSAGE - B6
POST {{hostUrl}}/room/add-room-message/1
Content-Type: application/json

{
"userId": 1,
"messageText": "Test 333"
}

### GET ROOM MESSAGES - B4
GET {{hostUrl}}/room/get-room-messages/1

### GET APPROVED ROOM USERS
GET {{hostUrl}}/roomUser/get-approved-room-users/room/1

### APPROVE/LEAVE ROOM - B5
### updatedBy must differ from user being update
PATCH {{hostUrl}}/roomUser/update-room-user/room/1/user/1
Content-Type: application/json

{
"updatedBy": 6,
"approvalStatus": "approved"
}

### GET ALL ROOM MESSAGES AFTER SPECIFIC USER JOIN
GET {{hostUrl}}/room/get-room-messages-after-join/room/1/user/1

### LOGIN
POST {{hostUrl}}/auth/login
Content-Type: application/json

{
"username": "testUser1234",
"password": "RealFilip33!"
}