# all routes except adding user are protected, login first
# only some routes are listed here

### ADD USER
POST {{hostUrl}}/user/add-user
Content-Type: application/json

{
"firstName": "yo",
"lastName": "Doe",
"username": "testUser1234",
"roleId": 1,
"email": "johndoe@example.com",
"password": "RealFilip33!",
"phoneNumber": "+1234567890",
"countryId": 123
}

### GET USERS
GET {{hostUrl}}/user/get-users
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET USER
# accessible only for admin (for test)
GET {{hostUrl}}/user/getUserById/2
Authorization: Bearer {{accessToken}}

### ADD COUNTRY
POST {{hostUrl}}/country/add-country
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
"name": "United States",
"countryCode": "US",
"locale": "en-US"
}

### GET COUNTRIES
GET {{hostUrl}}/country/get-countries
Authorization: Bearer {{accessToken}}

### ADD ROOM - B2, B6
POST {{hostUrl}}/room/add-room
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
"name": "testna 5"
}

### GET ROOMS - BASIC TASK 1 (B1)
GET {{hostUrl}}/room/get-rooms
Authorization: Bearer {{accessToken}}

### ROOM JOIN REQUEST - B3
POST {{hostUrl}}/roomUser/add-room-user/4
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
}

### SEND/ADD MESSAGE - B6
POST {{hostUrl}}/room/add-room-message/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
"userId": 1,
"messageText": "Test 333"
}

### GET ROOM MESSAGES - B4
GET {{hostUrl}}/room/get-room-messages/1
Authorization: Bearer {{accessToken}}

### GET APPROVED ROOM USERS
GET {{hostUrl}}/roomUser/get-approved-room-users/room/1
Authorization: Bearer {{accessToken}}

### APPROVE/LEAVE ROOM - B5
# updatedBy must differ from user being updated
PATCH {{hostUrl}}/roomUser/update-room-user/room/1/user/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
"updatedBy": 6,
"approvalStatus": "approved"
}

### GET ALL ROOM MESSAGES AFTER SPECIFIC USER JOIN
GET {{hostUrl}}/room/get-room-messages-after-join/room/1/user/1
Authorization: Bearer {{accessToken}}

### LOGIN
POST {{hostUrl}}/auth/login
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
"username": "testUser1234",
"password": "RealFilip33!"
}

### LOGOUT
# TODO: still in progress
POST {{hostUrl}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### GET PROFILE (TEST PROTECTED ROUTE IF NOT LOGGED IN)
# deprecated -> now global auth guard is used
GET {{hostUrl}}/profile

### SENT ROOM JOIN INVITATION
POST {{hostUrl}}/room/send-room-join-invitation

{

}