import { MigrationInterface, QueryRunner } from "typeorm";

export class GeneratedMigrationTest1715498239992 implements MigrationInterface {
    name = 'GeneratedMigrationTest1715498239992'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP FOREIGN KEY \`fk_room_users_room\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP FOREIGN KEY \`fk_room_users_user\``);
        await queryRunner.query(`ALTER TABLE \`room\` DROP FOREIGN KEY \`fk_room_created_by\``);
        await queryRunner.query(`ALTER TABLE \`message\` DROP FOREIGN KEY \`fk_messages_room\``);
        await queryRunner.query(`ALTER TABLE \`message\` DROP FOREIGN KEY \`fk_messages_user\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`fk_users_country\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`fk_users_role\``);
        await queryRunner.query(`DROP INDEX \`hash\` ON \`room_user\``);
        await queryRunner.query(`DROP INDEX \`username\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`email\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`phone_number\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`name\` ON \`country\``);
        await queryRunner.query(`DROP INDEX \`country_code\` ON \`country\``);
        await queryRunner.query(`ALTER TABLE \`room\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`message\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP COLUMN \`left_at\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD \`left_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP COLUMN \`hash\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD \`hash\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD UNIQUE INDEX \`IDX_0d67793619e16bcd7f0be380e8\` (\`hash\`)`);
        await queryRunner.query(`ALTER TABLE \`room_user\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`room_user\` CHANGE \`room_id\` \`room_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`room\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`room\` CHANGE \`is_private\` \`is_private\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`message\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`message\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`message\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`first_name\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`first_name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`last_name\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`last_name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`username\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`username\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD UNIQUE INDEX \`IDX_78a916df40e02a9deb1c4b75ed\` (\`username\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`last_active_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`last_active_at\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`phone_number\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`country\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`country\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`country\` ADD UNIQUE INDEX \`IDX_2c5aa339240c0c3ae97fcc9dc4\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`country\` DROP COLUMN \`country_code\``);
        await queryRunner.query(`ALTER TABLE \`country\` ADD \`country_code\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`country\` ADD UNIQUE INDEX \`IDX_13cc5bd0f95d2c5d9b3f07921c\` (\`country_code\`)`);
        await queryRunner.query(`ALTER TABLE \`country\` DROP COLUMN \`locale\``);
        await queryRunner.query(`ALTER TABLE \`country\` ADD \`locale\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`country\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`country\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD CONSTRAINT \`FK_48e3504326b5bb6aba15d119a11\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD CONSTRAINT \`FK_90d278bf002394670a9b557fcef\` FOREIGN KEY (\`room_id\`) REFERENCES \`room\`(\`room_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD CONSTRAINT \`FK_efe02daf5066198d601ade48bb8\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`message\` ADD CONSTRAINT \`FK_a9edf3bbd4fc17c42ee8677b9ce\` FOREIGN KEY (\`room_id\`) REFERENCES \`room\`(\`room_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`message\` ADD CONSTRAINT \`FK_54ce30caeb3f33d68398ea10376\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`message\` DROP FOREIGN KEY \`FK_54ce30caeb3f33d68398ea10376\``);
        await queryRunner.query(`ALTER TABLE \`message\` DROP FOREIGN KEY \`FK_a9edf3bbd4fc17c42ee8677b9ce\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP FOREIGN KEY \`FK_efe02daf5066198d601ade48bb8\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP FOREIGN KEY \`FK_90d278bf002394670a9b557fcef\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP FOREIGN KEY \`FK_48e3504326b5bb6aba15d119a11\``);
        await queryRunner.query(`ALTER TABLE \`country\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`country\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`country\` DROP COLUMN \`locale\``);
        await queryRunner.query(`ALTER TABLE \`country\` ADD \`locale\` varchar(30) NULL`);
        await queryRunner.query(`ALTER TABLE \`country\` DROP INDEX \`IDX_13cc5bd0f95d2c5d9b3f07921c\``);
        await queryRunner.query(`ALTER TABLE \`country\` DROP COLUMN \`country_code\``);
        await queryRunner.query(`ALTER TABLE \`country\` ADD \`country_code\` varchar(2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`country\` DROP INDEX \`IDX_2c5aa339240c0c3ae97fcc9dc4\``);
        await queryRunner.query(`ALTER TABLE \`country\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`country\` ADD \`name\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`phone_number\` varchar(40) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`email\` varchar(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`last_active_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`last_active_at\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP INDEX \`IDX_78a916df40e02a9deb1c4b75ed\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`username\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`username\` varchar(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`last_name\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`last_name\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`first_name\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`first_name\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`message\` CHANGE \`user_id\` \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`message\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`message\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`room\` CHANGE \`is_private\` \`is_private\` tinyint(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`room\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`room_user\` CHANGE \`room_id\` \`room_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`room_user\` CHANGE \`user_id\` \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP INDEX \`IDX_0d67793619e16bcd7f0be380e8\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP COLUMN \`hash\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD \`hash\` varchar(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP COLUMN \`left_at\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD \`left_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`room_user\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD \`updated_at\` timestamp(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`message\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`room\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`country_code\` ON \`country\` (\`country_code\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`name\` ON \`country\` (\`name\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`phone_number\` ON \`user\` (\`phone_number\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`email\` ON \`user\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`username\` ON \`user\` (\`username\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`hash\` ON \`room_user\` (\`hash\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`fk_users_role\` FOREIGN KEY (\`role_id\`) REFERENCES \`role\`(\`role_id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`fk_users_country\` FOREIGN KEY (\`country_id\`) REFERENCES \`country\`(\`country_id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`message\` ADD CONSTRAINT \`fk_messages_user\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`user_id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`message\` ADD CONSTRAINT \`fk_messages_room\` FOREIGN KEY (\`room_id\`) REFERENCES \`room\`(\`room_id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`room\` ADD CONSTRAINT \`fk_room_created_by\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`user_id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD CONSTRAINT \`fk_room_users_user\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`user_id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`room_user\` ADD CONSTRAINT \`fk_room_users_room\` FOREIGN KEY (\`room_id\`) REFERENCES \`room\`(\`room_id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
    }

}
